2023-01-14 10:22:47,578 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:28:30,326 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:30:22,254 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:32:29,336 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:35:54,434 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:41:18,209 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:41:44,663 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:42:42,439 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:43:03,042 — ERROR — db_writer.py:125 —       save_to_influx() — Error during central-INFLUX db insertion: 'InfluxErrManager' object has no attribute 'iaq_bucket'
2023-01-14 10:43:04,284 — ERROR — db_writer.py:125 —       save_to_influx() — Error during central-INFLUX db insertion: 'InfluxErrManager' object has no attribute 'iaq_bucket'
2023-01-14 10:43:07,539 — ERROR — db_writer.py:125 —       save_to_influx() — Error during central-INFLUX db insertion: 'InfluxErrManager' object has no attribute 'iaq_bucket'
2023-01-14 10:43:12,710 — ERROR — db_writer.py:125 —       save_to_influx() — Error during central-INFLUX db insertion: 'InfluxErrManager' object has no attribute 'iaq_bucket'
2023-01-14 10:43:20,330 — ERROR — db_writer.py:125 —       save_to_influx() — Error during central-INFLUX db insertion: 'InfluxErrManager' object has no attribute 'iaq_bucket'
2023-01-14 10:43:44,334 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:44:04,998 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 10:44:15,489 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 10:44:25,985 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 10:44:36,493 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 10:52:45,307 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:53:05,951 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 10:56:53,837 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 10:59:35,713 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:00:11,683 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:00:32,340 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:00:42,830 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:00:53,320 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:01:34,330 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:01:54,995 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:02:05,521 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:02:16,132 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:02:26,635 — ERROR — local_db_manager.py:93 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:03:25,311 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:03:45,979 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:03:56,475 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:06:11,501 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:06:32,183 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:06:42,681 — ERROR — local_db_manager.py:94 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:14:01,372 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:14:22,058 — ERROR — local_db_manager.py:96 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:15:27,432 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:16:54,472 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:21:17,526 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:21:20,018 — ERROR — local_db_manager.py:96 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:21:23,032 — ERROR — local_db_manager.py:96 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:21:26,034 — ERROR — local_db_manager.py:96 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:22:31,859 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:28:03,950 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:28:06,420 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:28:09,422 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:28:12,432 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:28:38,393 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:28:40,897 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:28:43,900 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:28:46,905 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:30:46,557 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:30:48,731 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:30:51,730 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:30:54,737 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:35:41,958 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:35:44,136 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:35:47,130 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:35:50,136 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:37:57,020 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:37:59,539 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:38:02,537 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:38:05,531 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:49:33,429 — ERROR — link_to_sensor.py:117 —           dummy_read() — Failed to read sensor: 
2023-01-14 11:49:35,959 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:49:38,961 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 11:49:41,968 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:36:12,503 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:36:35,287 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:36:43,031 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:41:02,216 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:41:04,717 — ERROR — local_db_manager.py:90 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'cursor'
2023-01-14 13:41:07,719 — ERROR — local_db_manager.py:90 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'cursor'
2023-01-14 13:41:48,209 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:42:12,357 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:42:14,834 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:42:14,992 — ERROR — local_db_manager.py:105 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,2.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:42:17,839 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:42:17,999 — ERROR — local_db_manager.py:105 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,3.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:42:20,848 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:42:21,007 — ERROR — local_db_manager.py:105 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,4.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:42:52,925 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:42:55,396 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:42:55,567 — ERROR — local_db_manager.py:104 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,2.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:42:58,396 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:42:58,564 — ERROR — local_db_manager.py:104 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,3.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:43:01,404 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:43:01,570 — ERROR — local_db_manager.py:104 —     save_to_local_db() — Error during local db insertion: INSERT INTO iaq (Timestamp, temperature, RH, dew_point, abs_humidity, co2, voc_index, voc_acc, voc_eq_co2, luminance, turned_on) VALUES (NOW(),23.2,30.1,4.1,3.3,1000.1,700.1,NULL,700.1,234.4,4.0)    except: local variable 'cursor' referenced before assignment
2023-01-14 13:43:57,697 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 13:44:00,189 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:44:03,195 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:44:06,200 — ERROR — local_db_manager.py:89 —     save_to_local_db() — Error connecting to local DB 'NoneType' object has no attribute 'ping'
2023-01-14 13:44:43,694 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 14:10:30,699 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 14:11:02,634 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 14:12:02,691 — ERROR — link_to_sensor.py:118 —           dummy_read() — Failed to read sensor: 
2023-01-14 14:14:22,053 — ERROR — link_to_sensor.py:119 —           dummy_read() — Failed to read sensor: 
2023-01-14 14:15:22,115 — ERROR — link_to_sensor.py:119 —           dummy_read() — Failed to read sensor: 
